---
include:
  - board: eyelash_sofle_left
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_BLE=y -DCONFIG_ZMK_SPLIT_BLE=y -DCONFIG_ZMK_BLE_CLEAR_BONDS_ON_START=y
    artifact-name: eyelash_sofle_left

  - board: eyelash_sofle_right
    shield: nice_view
    cmake-args: -DCONFIG_ZMK_BLE=y -DCONFIG_ZMK_SPLIT_BLE=y
    artifact-name: eyelash_sofle_right

  - board: eyelash_sofle_left
    shield: settings_reset
    artifact-name: settings_reset
